---
editor_options:
  chunk_output_type: console
---
```{r data-analysis-setup}
library(tidyverse)
library(data.table)
library(lme4)
# library(afex)
# library(brms)
library(sjPlot)

compute_new = FALSE
```

```{r}
analysis_data <- full_data %>% 
  filter(phase == "test") %>% 
  filter(!is.na(repeated), !is.na(response)) %>% 
  mutate(
    truth_instruction_timing = ifelse(
      truth_instruction_timing == "",
      "none",
      truth_instruction_timing
    ),
    repetition_instruction_timing = ifelse(
      repetition_instruction_timing == "",
      "none",
      repetition_instruction_timing
    ),
    repetition_time_type = case_when(
      repetition_time <= 5 ~ "immediate",
      repetition_time > 5 & repetition_time <= 60 ~ "delay",
      repetition_time > 60*24 ~ "next_day"
    )
  ) %>% 
  mutate(
    truth_instruction_timing = fct_relevel(
      factor(truth_instruction_timing),
      "none",
      "exposure", 
      "test",
      "both"
    ),
    repetition_instruction_timing = fct_relevel(
      factor(repetition_instruction_timing),
      "none",
      "exposure", 
      "test",
      "both"
    ),
    repetition_time_type = fct_relevel(
      factor(repetition_time_type),
      "immediate",
      "delay", 
      "next_day"
    ),
  )

has_complete_data <- analysis_data %>% 
  count(procedure_id, subject, repeated) %>% 
  count(procedure_id, subject) %>% 
  mutate(
    has_complete_data = ifelse(n == 2, 1, 0)
  )

analysis_data <- analysis_data %>% 
  left_join(
    ., has_complete_data
  ) %>% 
  filter(has_complete_data == 1) 

prop_true <- analysis_data %>% 
  group_by(statement_id) %>% 
  summarize(
    proportion_true = mean(response, na.rm = TRUE)
  )
  
analysis_data <- analysis_data %>% 
  left_join(prop_true)

dichotomous_data <- analysis_data %>% 
  filter(truth_rating_scale == "dichotomous")

scale_data <- analysis_data %>% 
  filter(truth_rating_scale != "dichotomous")
```

```{r}
# Number of participants, age, laboratory status, scale
long_study_data <- study_overview %>% 
  mutate_all(as.character) %>% 
  select(truth_rating_scale, truth_rating_steps, filler_task_yesno) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value")

plot_study_data <- long_study_data %>%
  count(variable, value) %>% 
  mutate(
    value = fct_relevel(
      factor(value),
      "101", "range", "likert", "11", "6", "5", "4", "dichotomous", "2"
    )
  )

study_overview_plot <- ggplot(plot_study_data, aes(x = variable, y = n, fill = value)) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = paste0(value, " (", n, ")")),
    position = position_stack(vjust = 0.5),
    color = "black",
    size = 3
  ) +
  labs(
    title = "Breakdown of Study Variables",
    x = NULL,
    y = "Count"
  ) +
  scale_fill_grey(start = 0.3, end = 0.8) +  # Adjust range for lighter/darker contrast
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )+
  coord_flip()

# Reshape data to long format
long_procedure_data <- procedure_data %>%
  filter(phase == "test") %>% 
  select(
    repetition_instructions, repetition_instruction_timing,
    truth_instructions, truth_instruction_timing,
    presentation_type, repetition_type, repetition_location,
    percent_repeated
    ) %>%  # Add more vars if needed
  mutate_all(as.character) %>% 
  mutate(
    repetition_instructions = ifelse(
      repetition_instructions == "1", "yes", "no"
    ),
    repetition_instruction_timing = ifelse(
      repetition_instruction_timing == "",
      "none", repetition_instruction_timing
    ),
    truth_instructions = ifelse(
      truth_instructions == "1", "yes", "no"
    ),
    truth_instruction_timing = ifelse(
      truth_instruction_timing == "",
      "none", truth_instruction_timing
    ),
    percent_repeated = case_when(
      percent_repeated %in% c("66", "67", "66.67") ~ "66",
      TRUE ~percent_repeated
    ),
    repetition_type = ifelse(repetition_type == "some exact, some semantic (incongruent)", "mixed", repetition_type)
  ) %>% 
  mutate(
    truth_instruction_timing = fct_relevel(
      factor(truth_instruction_timing),
      "both", "exposure", "test", "none"
    ),
    repetition_instruction_timing = fct_relevel(
      factor(repetition_instruction_timing),
      "both", "exposure", "test", "none"
    )
  ) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value")

# Count combinations of variable and value
plot_procedure_data <- long_procedure_data %>%
  count(variable, value) %>% 
  mutate(
    value = fct_relevel(
      factor(value),
      "paraphrase", "exact","no", "none", "yes", "both", "exposure", "test", 
      "100", "67", "66.67", "66", "50", "46.67", "33", "0", "mixed"
    )
  )

# Plot
procedure_overview_plot <- ggplot(plot_procedure_data, aes(x = variable, y = n, fill = value)) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = paste0(value, " (", n, ")")),
    position = position_stack(vjust = 0.5),
    color = "black",
    size = 3
  ) +
  labs(
    title = "Breakdown of Procedure Variables",
    x = NULL,
    y = "Count"
  ) +
  scale_fill_grey(start = 0.3, end = 0.8) +  # Adjust range for lighter/darker contrast
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )+
  coord_flip()
```


```{r}
if (compute_new == TRUE){
  model_check_dichotomous <- glmer(
    response ~ repeated + (1 | subject) + (1 | statement_id) + (1 | procedure_id),
    data = dichotomous_data,
    family = binomial()
  )
  
  model_nosubject_re_dichotomous <- glmer(
    response ~ repeated + (1 | subject) + (1 + repeated | statement_id) + (1 + repeated | procedure_id),
    data = dichotomous_data,
    family = binomial()
  )
  
  model_nostatement_re_dichotomous <- glmer(
    response ~ repeated + (1 + repeated | subject) + (1 | statement_id) + (1 + repeated | procedure_id),
    data = dichotomous_data,
    family = binomial()
  )
  
  model_noprocedure_re_dichotomous <- glmer(
    response ~ repeated + (1 + repeated | subject) + (1 + repeated | statement_id) + (1 | procedure_id),
    data = dichotomous_data,
    family = binomial()
  )
  
  model_full_re_dichotomous <- glmer(
    response ~ repeated + (1 + repeated | subject) + (1 + repeated | statement_id) + (1 + repeated | procedure_id),
    data = dichotomous_data,
    family = binomial()
  )
  
  ## Scale data
  model_check_scale <- lmer(
    response ~ repeated + (1 | subject) + (1 | statement_id) + (1 | procedure_id),
    data = scale_data, 
    control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)),
    REML = FALSE
  )
  
  model_nosubject_re_scale <- lmer(
    response ~ repeated + (1 | subject) + (1 + repeated | statement_id) + (1 + repeated | procedure_id),
    data = scale_data, 
    control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)),
    REML = FALSE
  )
  
  model_nostatement_re_scale <- lmer(
    response ~ repeated + (1 + repeated | subject) + (1 | statement_id) + (1 + repeated | procedure_id),
    data = scale_data, 
    control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)),
    REML = FALSE
  )
  
  model_noprocedure_re_scale <- lmer(
    response ~ repeated + (1 + repeated | subject) + (1 + repeated | statement_id) + (1 | procedure_id),
    data = scale_data, 
    control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)),
    REML = FALSE
  )
  
  model_full_re_scale <- lmer(
    response ~ repeated + (1 + repeated | subject) + (1 + repeated | statement_id) + (1 + repeated | procedure_id),
    data = scale_data, 
    control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)),
    REML = FALSE
  )
  
  save(model_check_dichotomous, file = "./markdown/data/model_check_dichotomous.Rdata")
  save(model_check_scale, file = "./markdown/data/model_check_scale.Rdata")
  save(model_nosubject_re_dichotomous, file = "./markdown/data/model_nosubject_re_dichotomous.Rdata")
  save(model_nosubject_re_scale, file = "./markdown/data/model_nosubject_re_scale.Rdata")
  save(model_nostatement_re_dichotomous, file = "./markdown/data/model_nostatement_re_dichotomous.Rdata")
  save(model_nostatement_re_scale, file = "./markdown/data/model_nostatement_re_scale.Rdata")
  save(model_noprocedure_re_dichotomous, file = "./markdown/data/model_noprocedure_re_dichotomous.Rdata")
  save(model_noprocedure_re_scale, file = "./markdown/data/model_noprocedure_re_scale.Rdata")
  save(model_full_re_dichotomous, file = "./markdown/data/model_full_re_dichotomous.Rdata")
  save(model_full_re_scale, file = "./markdown/data/model_full_re_scale.Rdata")   
} else {
  load(file = "./markdown/data/model_check_dichotomous.Rdata")
  load(file = "./markdown/data/model_check_scale.Rdata")
  load(file = "./markdown/data/model_nosubject_re_dichotomous.Rdata")
  load(file = "./markdown/data/model_nosubject_re_scale.Rdata")
  load(file = "./markdown/data/model_nostatement_re_dichotomous.Rdata")
  load(file = "./markdown/data/model_nostatement_re_scale.Rdata")
  load(file = "./markdown/data/model_noprocedure_re_dichotomous.Rdata")
  load(file = "./markdown/data/model_noprocedure_re_scale.Rdata")
  load(file = "./markdown/data/model_full_re_dichotomous.Rdata")
  load(file = "./markdown/data/model_full_re_scale.Rdata") 
}

model_comp_scale <- anova(
  model_check_scale, 
  model_nosubject_re_scale,
  model_noprocedure_re_scale, 
  model_nostatement_re_scale,
  model_full_re_scale
  )

model_comp_dichotomous <- anova(
  model_check_dichotomous, 
  model_nosubject_re_dichotomous,
  model_noprocedure_re_dichotomous, 
  model_nostatement_re_dichotomous,
  model_full_re_dichotomous
)

tab_model(
  model_check_scale,
  model_full_re_scale,
  model_nosubject_re_scale,
  model_noprocedure_re_scale,
  model_nostatement_re_scale,
  show.re.var = TRUE,  # Show random effect variances
  show.icc = TRUE,     # Show ICC
  show.loglik = TRUE,
  show.aic = TRUE,
  show.bic = TRUE,
  dv.labels = c("Check", "Full", "No Subject RE", "No Procedure RE", "No Statement RE"),
  title = "Multilevel Model Comparison: Scale Data"
)

tab_model(
  model_check_dichotomous, 
  model_nosubject_re_dichotomous,
  model_noprocedure_re_dichotomous, 
  model_nostatement_re_dichotomous,
  model_full_re_dichotomous
  # show.re.var = TRUE,  # Show random effect variances
  # # show.icc = TRUE,     # Show ICC
  # show.loglik = TRUE,
  # show.aic = TRUE,
  # show.bic = TRUE,
  # dv.labels = c("Check", "Full", "No Subject RE", "No Procedure RE", "No Statement RE"),
  # title = "Multilevel Model Comparison: Scale Data"
)
```


```{r}
if (compute_new == TRUE){
  # Retentions-Intervall Länge noch mit aufnehmen?
  model_re_likert_sameday <- lmer(
    response ~ repeated + (1 + repeated | subject) + (1 + repeated | statement_id) + (1 + repeated | procedure_id),
    data = scale_data %>% filter(repetition_time <= 180),
    REML = FALSE
  )
  
  model_re_likert_later <- lmer(
    response ~ repeated + (1 + repeated | subject) + (1 + repeated | statement_id) + (1 + repeated | procedure_id),
    data = scale_data %>% filter(repetition_time > 180),
    REML = FALSE
  )
  
  # summary(model_re_likert_sameday)
  # summary(model_re_likert_later)
  # 
  # VarCorr(model_re_likert_sameday)
  # VarCorr(model_re_likert_later)
  
  save(model_re_likert_sameday, file = "./markdown/data/model_re_likert_sameday.Rdata")
  save(model_re_likert_later, file = "./markdown/data/model_re_likert_later.Rdata")
} else {
  load(file = "./markdown/data/model_re_likert_sameday.Rdata")
  load(file = "./markdown/data/model_re_likert_later.Rdata")
}

```




```{r, eval = FALSE}
prep_aov <- function(data){
  data %>% 
    group_by(subject, repeated) %>% 
    summarize(mean_resp = mean(response, na.rm = FALSE))
}

run_simple_aov <- function(data) {
  aov_ez(
    id = "subject",
    dv = "mean_resp",
    within = "repeated",
    data = data
  )
}

run_lme4 <- function(data){
  lme4::lmer(response ~ repeated + (1 | subject), data = data)
}

results <- analysis_data %>% 
  nest(.by = c(procedure_id, repetition_time, n_statements)) %>% 
  mutate(
    aov_data = map(data, prep_aov),
  )
  
results <- results %>% 
  mutate(
    n_trials = map_dbl(data, nrow),
    n_subjects = map_dbl(data, ~length(unique(.$subject))),
    aov_results = map(aov_data, run_simple_aov)
  )

results <- results %>% 
  mutate(
    eta_sq = map_dbl(aov_results, ~effectsize::eta_squared(.) %>% pull(Eta2_partial)),
    omega_sq = map_dbl(aov_results, ~effectsize::omega_squared(.) %>% pull(Omega2_partial))
  )

results <- results %>% 
  mutate(
    mlm = map(data, run_lme4)
  )

results$eta_sq %>% hist(breaks = 10)
results$omega_sq %>% hist()
```