---
editor_options:
  chunk_output_type: console
---
<!-- # Library calls -->
```{r data-prep-setup}
library(tidyverse)
library(data.table)
library(acdcquery)
```

```{r}
conn <- connect_to_db("./markdown/data/ted.db")

all_argument <- list() %>% 
  add_argument(
    conn,
    "publication_id",
    "greater",
    "0"
  )

```

```{r, message=FALSE, echo = FALSE}
publications_overview <- query_db(
  conn,
  all_argument,
  "default",
  "publication_table"
)

study_overview <- query_db(
  conn,
  all_argument,
  "default",
  "study_table"
)

procedure_data <- query_db(
  conn,
  all_argument %>% 
    add_argument(
      conn,
      "phase",
      "equal",
      "test"
    ),
  "default",
  "procedure_table"
)

full_data <- query_db(
  conn,
  all_argument,
  c("default", "study_id", "publication_id", "statement_text", "statement_accuracy", "statementset_id", "statementset_publication", "within_description", "between_description", "repetition_time", "n_statements", "phase", "truth_instructions", "repetition_instructions", "truth_instruction_timing", "repetition_instruction_timing", "truth_rating_scale", "truth_rating_steps"),
  "observation_table"
)

references_table <- query_db(
  conn,
  all_argument,
  c("publication_id", "authors", "conducted", "peer_reviewed", "study_id", "n_participants"),
  "publication_table"
)

trial_nums <- full_data %>% 
  count(study_id) %>% 
  rename("n_trials" = "n")

references_table <- references_table %>% 
  left_join(., trial_nums) %>% 
  mutate(
    peer_reviewed = ifelse(peer_reviewed == 1, "Yes", "No")
  )

# data.table::fwrite(full_data, "./markdown/data/full_data.csv")
```


