---
title             : "Introducing the Truth Effect Database (TED) - an open trial-level database promoting FAIR data in truth effect research"
shorttitle        : "Introducing TED"

author: 
  - name          : "Sven Lesche"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Hauptstraße 47-51, 69117 Heidelberg"
    email         : "sven.lesche@psychologie.uni-heidelberg.de"
    # role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
  - name          : "Annika Stump"
    affiliation   : "2"
    # role:
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
affiliation:
  - id            : "1"
    institution   : "Ruprecht-Karls-University Heidelberg"
  - id            : "2"
    institution   : "Albert-Ludwigs-University Freiburg"
  # add a second id using this syntax

authornote: |
  

abstract: |
  The FAIR data principles form the foundation of the open data movement. However, while many current practices ensure data are findable and accessible, true interoperability and reusability remain limited. This paper introduces the Truth Effect Database (TED), a large-scale, trial-level, open database harmonizing data from illusory truth effect studies designed to enhance interoperability and reusability. TED currently integrates data from 59 studies in 29 publications, spanning 12,242 participants and 808,231 trials, accounting for a wide range of dispositional and contextual variables. To promote usability, TED focuses on user-friendly data submission using a custom entry website and data extraction using the R-package acdcquery. These tools guide researchers through both data entry and retrieval, eliminating the need for direct interaction with the database’s internal structure. We illustrated the utility of TED through Bayesian multilevel analyses, highlighting substantial variance in the illusory truth effect at the subject level, moderated by the delay between exposure and judgment phases in truth effect paradigms. Beyond this first demonstration, TED provides the foundation for a wide range of future research. These include (living) meta-analyses, simulation-based power analyses, rigorous replication and reanalysis of existing studies, as well as the validation and development of formal cognitive models. As an open and extensible infrastructure, TED serves as a blueprint for sustainable, community-driven database development in psychological science.
  
keywords          : "illusory truth effect, open science, open data, database, SQL, reproducibility"
# wordcount         : "X"

bibliography      : ["r-references.bib", "truth_effect.bib"] # put your ref files here

floatsintext      : yes # for pics in text
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no
link-citations    : true # custom addin, makes citations link to reference section
# figsintext        : yes # custom addin

classoption       : "man"
# the settings below allow compilation of APA7 style citations/documents
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - | 
    \raggedbottom
  - |
    \usepackage{hhline}
  - |
    \setlength{\parskip}{0pt}

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
output            : papaja::apa6_pdf
---
```{r setup, include = FALSE}
# Working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# disallow tables breaking over pages
knitr::opts_chunk$set(ft.keepnext = TRUE,
                      ft.align = "left",
                      ft.latex.float = "float")
# Seed for random number generation
set.seed(1234)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed) # this adds random seed to all chunks
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

knitr::dep_auto()
```

<!-- Setup -->
```{r child = "markdown/setup.Rmd"}
```
<!-- Here we incorporate child markdown-documents as the separate parts -->

<!-- Introduction -->
```{r child = "markdown/introduction.Rmd"}
```

<!-- Method -->
```{r child = "markdown/method.Rmd"}
```

<!-- Results -->
```{r child = "markdown/results.Rmd"}
```

<!-- Discussion -->
```{r child = "markdown/discussion.Rmd"}
```

<!-- References -->
<!-- \newpage -->
<!-- # References -->
<!-- ::: {#refs custom-style="Bibliography"} -->
<!-- ::: -->

\newpage

<!-- # (APPENDIX) Appendix {-} -->

```{r child = "markdown/appendix.Rmd"}
```


